# Generated by Django 2.0.2 on 2018-03-10 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lumosuser',
            name='lumos_user',
        ),
        migrations.AlterField(
            model_name='lumosuser',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lumos_user', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
