# Generated by Django 2.0.2 on 2018-03-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180310_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='lumosuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
