# Generated by Django 2.0.2 on 2018-03-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_lumosuser_is_verified'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lumosuser',
            table='lumos_user',
        ),
    ]
