# Generated by Django 2.0.2 on 2018-02-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.URLField(blank=True)),
                ('domains_for', models.CharField(choices=[('TS', 'TECHNICAL_SKILLS'), ('SS', 'SOFT_SKILLS')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('skill_level', models.CharField(choices=[('BG', 'BEGINNER'), ('IT', 'INTERMEDIATE'), ('AD', 'ADVANCED')], max_length=2)),
                ('link_url', models.URLField(unique=True)),
                ('external_type', models.CharField(choices=[('BL', 'BLOG'), ('TU', 'TUTORIAL'), ('CO', 'COURSE')], max_length=2)),
                ('paid', models.BooleanField(default=False)),
                ('domains', models.ManyToManyField(related_name='externallink_domains', to='courses.Domain')),
            ],
            options={
                'ordering': ['external_type'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('site_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.URLField(blank=True)),
                ('languages_for', models.CharField(choices=[('TS', 'TECHNICAL_SKILLS'), ('SS', 'SOFT_SKILLS')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('skill_level', models.CharField(choices=[('BG', 'BEGINNER'), ('IT', 'INTERMEDIATE'), ('AD', 'ADVANCED')], max_length=2)),
                ('video_url', models.URLField(unique=True)),
                ('domains', models.ManyToManyField(related_name='video_domains', to='courses.Domain')),
                ('languages', models.ManyToManyField(related_name='video_languages', to='courses.Language')),
            ],
            options={
                'ordering': ['-modified_at', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='language',
            unique_together={('language_name', 'slug')},
        ),
        migrations.AddField(
            model_name='externallink',
            name='languages',
            field=models.ManyToManyField(related_name='externallink_languages', to='courses.Language'),
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together={('domain_name', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('title', 'slug')},
        ),
    ]
