# Generated by Django 2.0.2 on 2018-04-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomdata',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
