# Generated by Django 2.0.2 on 2018-04-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180403_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='_knowledgebase_prerequisites_+', to='courses.KnowledgeBase'),
        ),
        migrations.AlterUniqueTogether(
            name='tags',
            unique_together={('tag', 'slug')},
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='knowledgebase_tag', to='courses.Tags'),
        ),
        migrations.AddField(
            model_name='randomdata',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='randomdata_tag', to='courses.Tags'),
        ),
        migrations.AddField(
            model_name='softskillsdata',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='softskillsdata_tag', to='courses.Tags'),
        ),
    ]
